apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cat-bonnets-rest-v1
  description: The API for doing things with cat bonnets
  tags:
    - cats
    - rest
    - bonnets
spec:
  type: openapi
  lifecycle: experimental
  owner: engineering
  definition:
    $text: https://github.com/RoadieHQ/sample-service/blob/main/api-spec.yaml
