apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cat-bonnets
  description: A digital cat bonnets API.
  links:
    - title: A notion page about life at snyk
      url: https://www.notion.so/snyk/Life-Snyk-5aafa9d01d644a4aadc28c7474751bcf
  tags:
    - cats
    - rest
    - bonnets
  annotations:
    github.com/project-slug: jbowes/cat-bonnets
    backstage.io/techdocs-ref: url:https://github.com/jbowes/cat-bonnets/tree/main
spec:
  type: service
  lifecycle: experimental
  owner: jbowes
  system: bonnet-commerce
  providesApis:
    - cat-bonnets-rest-v1

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cat-bonnets-rest-v1
  description: The API for doing things with cat bonnets
  tags:
    - cats
    - rest
    - bonnets
spec:
  type: openapi
  lifecycle: experimental
  owner: engineering
  system: bonnet-commerce
  definition:
    $text: https://github.com/RoadieHQ/sample-service/blob/main/api-spec.yaml
