apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cat-bonnets
  description: A digital cat bonnets API.
  links:
    - title: A notion page about life at snyk
      url: https://www.notion.so/snyk/Life-Snyk-5aafa9d01d644a4aadc28c7474751bcf
      icon: dashoard
  tags:
    - cats
    - rest
    - bonnets
  annotations:
    github.com/project-slug: jbowes/cat-bonnets
    backstage.io/techdocs-ref: url:https://github.com/jbowes/cat-bonnets/tree/main
spec:
  type: service
  lifecycle: experimental
  owner: jbowes
  system: bonnet-commerce
  providesApis:
    - cat-bonnets-rest-v1
